# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38e19fb31d129365a8852efc4847303d198da2efc0e7a24f38f92a87a1914a5878d2c2619a16c098a355b05acd4e69e2ecfe74e8b178815c81245d360ef9b03e

test:
  secret_key_base: 285487b92c061f0d2515e1e4dd991b5c61926cc2c45e5bc9c9e27119129f3eba4edb593e57dd2a64d50bb1040e2e2cd83b73cc1fa4776f9ac2e5426d53ca73ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 38e19fb31d129365a8852efc4847303d198da2efc0e7a24f38f92a87a1914a5878d2c2619a16c098a355b05acd4e69e2ecfe74e8b178815c81245d360ef9b03e